### ISSUE TITLE
Obfuscated url analysis page doesnt appear obfuscated

### ISSUE THREAD

**Issue by MLHale** [MLHale/GenCyber-web-content#13]
@robinagandhi I just finished the url analysis module review. The only problem I see is that [http://faculty.ist.unomaha.edu/rgandhi/phishing-demo/obfuscated.html](http://faculty.ist.unomaha.edu/rgandhi/phishing-demo/obfuscated.html) doesn't appear to be obfuscated. The source appears to be the same as [http://faculty.ist.unomaha.edu/rgandhi/phishing-demo/phishing.html](http://faculty.ist.unomaha.edu/rgandhi/phishing-demo/phishing.html)

**Comment by robinagandhi** [comment]
@MLHale, how did you view the source? I did not obfuscate all the source. I just encoded the URLs, so that they still see the webpage structure. Here is what I see in chrome for the obfuscated page:
<img width="854" alt="screen shot 2016-07-19 at 8 32 48 pm" src="https://cloud.githubusercontent.com/assets/16670362/16972323/2481050c-4df0-11e6-8c5f-8325dd5b60c1.png">

and here is the phishing regular page.

<img width="829" alt="screen shot 2016-07-19 at 8 34 23 pm" src="https://cloud.githubusercontent.com/assets/16670362/16972335/3c6a0240-4df0-11e6-9985-94516f01ef54.png">

**Comment by MLHale** [comment]
I just used inspect element (habit), didn't think about view-source.

(non-obfuscated)
![non-obfuscated](https://cloud.githubusercontent.com/assets/613794/16972647/cd725876-4df2-11e6-8383-080ccbc163ed.png)

(obfuscated)
![obfuscated](https://cloud.githubusercontent.com/assets/613794/16972662/e7764124-4df2-11e6-80a4-040055d69029.png)

Maybe one lesson here is to always inspect element over viewing source! =P

**Comment by robinagandhi** [comment]
I like it! I will add it to the lesson.

**Comment by robinagandhi** [comment]
@MLHale Do you think that these two modules (Email and Phishing) will need about hour and a half at least? If not, we can think about having them go through something like this for the apache server: https://www.digitalocean.com/community/tutorials/openssl-essentials-working-with-ssl-certificates-private-keys-and-csrs

**Comment by MLHale** [comment]
Probably best to allow an hour and a half I think. There are actually a lot of good exercises in there that will take some time to go through. I don't think we lack for content - which is why I just held off on ssl altogether. Abhishek will also give a 15 min talk about SSL.

**Comment by robinagandhi** [comment]
@MLHale Added the inspect element piece for obfuscation analysis. Very handy. I also fully obfuscated the page using an external JS file if you go to view source now. The JS file is also not very helpful as it uses math based manipulations for obfuscation.

**Comment by MLHale** [comment]
Nice!
